Algoritmo "semnome"
//Faça um algoritmo que:
// Leia um número inteiro;
// Leia um segundo número inteiro;
//Efetue a adição dos dois valores;
//Apresente o valor calculado.
Var
 n1,n2, resposta: inteiro
 
Inicio
Escreval ("Informe o primeiro número:")
leia(n1)

escreval ("Informe o segundo número:")
leia (n2)

resposta <- n1+ n2
escreval ("A resposta é: ", resposta)

resposta <- n1-n2
escreval ("A resposta é:" , resposta)

Fimalgoritmo