Algoritmo "semnome"
//  Faça um algoritmo que calcule e apresente o valor do volume de uma lata
// de óleo, utilizando a fórmula VOLUME = 3,14159 * RAIO * RAIO * ALTURA.

Var
volume,raio,altura:real

Inicio

volume<- 3.14159
escreval ("Calculo do volume")
escreval("==========================")
escreval ("Informe o raio da lata de óleo")
leia(raio)
escreval ("Informe a altura")
leia(altura)

volume <- 3.14159 * RAIO * RAIO * ALTURA
escreval ("O volume da lata de óleo é: ", Volume)

Fimalgoritmo