Algoritmo "Soma dos vetores"
//Faça um algoritmo que some o conteúdo de dois vetores e armazene o
//resultado em um terceiro vetor.
Var
V1: vetor [1..1] de inteiro
V2: vetor [1..1] de inteiro
V3: vetor [1..1] de inteiro


Inicio
Escreval ("Informe o primeiro valor para o vetor1:")
leia(v1[1])
Escreval ("Informe o segundo valor para o vetor2:")
leia (v2[1])

v3[1] <- v2[1]+ v1[1]
escreval ("A soma do vetor 1 + vetor 2 é:",v3[1])


Fimalgoritmo